name: vocal
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.7
  - icu=68.2
  - zip=3.0
  - biopython=1.79
  - pandas=1.3.3
  - pblat=2.5
  - r-base=4.0.5
  - r-optparse=1.7.1
  - r-readr=2.0.2
  - r-logger=0.2.2
  - r-lubridate=1.8.0
  - r-purrr=0.3.4
  - r-forcats=0.5.1
  - r-stringr=1.4.0
  - r-ggplot2=3.3.6
  - r-tidyr=1.2.0
  - r-dplyr=1.0.7
  - r-digest=0.6.28
  - r-igraph=1.2.7
  - requests=2.27.1
  - openpyxl=3.0.9
  - tqdm=4.62.3
  - markupsafe=2.0.1
  - jinja2=2.11.3
  - htmlmin=0.1.12
  - scikit-learn=1.1.1
  - pip:
    - pango_aliasor==0.2.0
